### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Drkoles** [systemo-biz/jquery-fancyindex-wp-cp#1]
Привет. Скрипт с ошибками, поэтому мне пришлось внести поправки. Я не понимаю, как мне ещё эти косяки исправлять? (например то, что заголовки постов не выводятся)

**Comment by aiiddqd** [comment]
Код. Покажи ошибку.

**Comment by aiiddqd** [comment]
Как так в примере работает. А у тебя вдруг нет. Что это за фантастика.

**Comment by Drkoles** [comment]
Ну вот здесь.Я прокомментировал строчку.
![js](https://cloud.githubusercontent.com/assets/10225107/5695992/97ec29e0-99dd-11e4-811d-68e90f02b35a.jpg)

**Comment by Drkoles** [comment]
Ну у меня опыта нет так то) Может туплю где то. Подскажи)

**Comment by Drkoles** [comment]
Для удобства
https://gist.github.com/Drkoles/8b740da08fe3c2cabbb5

**Comment by Drkoles** [comment]
4 строка. Если оставить html() - заголовки выводиться не будут.

**Comment by aiiddqd** [comment]
Не трогай компонент. Удали все что правил. Загрузи новый. Покажи код. Тот что использует компонент. Код плагина wp.

**Comment by aiiddqd** [comment]
Загрузи плагин целиком. Затем компонент знамени на оригинал. Так чтобы там не было твоих правок.

**Comment by aiiddqd** [comment]
Ссылку вставь сюда. Иначе ничего не понятно. А я не телепат.

**Comment by Drkoles** [comment]
Не сразу понял, что от меня требуется) Теперь всё ясно)
ссылка на оригинал:
https://github.com/Drkoles/Fancy.Index.script/commit/730fdef7aaff4a0c5ad0909dbbf069f67606e05d
ссылка на исправленную версию:
https://github.com/Drkoles/Fancy.Index.script/commit/72216e0a5390e3fdfcc0f7b426c95b4f1fd53b7f
Функцию $ пришлось заменить на jQuery. Так как на неё компилятор ругался. Может есть другой способ решения этой проблемы?

**Comment by aiiddqd** [comment]
что это?
дай мне ссылку, чтобы сказать, запустить и проверить.
как я могу скачать по тем ссылкам что ты указал и проверить?

**Comment by Drkoles** [comment]
Вот так? Плагин zip без правок:
https://github.com/Drkoles/Repos_orig
Плагин zip с правками:
https://github.com/Drkoles/Repos

**Comment by aiiddqd** [comment]
зчм эта мелочевка вынесена в отдельный файл?
https://github.com/Drkoles/Fancy.Index.script/blob/master/js/koko.js

пчм селектор на body?

если нам нужно содержимое только контента. так селектор надо на контент наводить.

**Comment by Drkoles** [comment]
На счёт селектора согласен. А отдельный файл сделал, потому что ты сказал, что нельзя в скрипте ничего менять)

**Comment by Drkoles** [comment]
Значит мне нужно:
- код из "файла с мелочевкой" перенести с код скрипта.
- поменять селектор.

**Comment by aiiddqd** [comment]
Все отличано работает.
Но:
1. надо чтобы работало только на постах. а оно везде работает. в том числе на списках и страницах.
2. должно брать только контент поста. Прочие заголовки не нужны. В идеале если будет брать только заголовки первого уровня.

**Comment by aiiddqd** [comment]
вот снимок http://monosnap.com/image/vrIQdMNigStWoiLKthC3BngnSTyiQC

**Comment by Drkoles** [comment]
У тебя работает без правок?

**Comment by aiiddqd** [comment]
да

**Comment by Drkoles** [comment]
Странно.А может быть дело в теме?

**Comment by Drkoles** [comment]
Если не заменить $ на jQuery - то у меня ругается компилятор. Почему скрипт без этой правки у меня не работает? Я запутался что то)

**Comment by Drkoles** [comment]
Заголовки в пределах поста теперь у меня выводятся и с помощью html().

**Comment by aiiddqd** [comment]
компилятор ругается мб потому что ты не обернул его http://wpcraft.ru/eshhe-odna-prichina-oshibki-uncaught-typeerror-undefined-is-not-a-function-v-wordpress-s-jquery/

**Comment by Drkoles** [comment]
Спасибо. Сейчас попробую.
А что бы работало только постах, можно использовать селектор 
jQuery".entry-content"

**Comment by Drkoles** [comment]
Да, ты прав) Не обернул) Заработал) 
Уточни пожалуйста что ты имел ввиду когда писал что в скрипте ничего нельзя менять?) 
Обернув его - я его изменил. ведь так)

**Comment by aiiddqd** [comment]
Нелья зменять компонент. Тот что ты копировал с GitHub. тот что писал другой автор. его работу нельзя менять.
Все остальное меняй сколько хочешь.

**Comment by Drkoles** [comment]
Ясно. Добавлять код можно, а изменять и удалять нельзя)

**Comment by aiiddqd** [comment]
Суть в обновляемости. Если мы берем компоненты у 3х лиц. То их менять нельзя.
Должна быть возможность их обновления. Вдруг автор выпустит новую версию.
И получается что если ты внес изменения в чужой компонент, то при обновлении это все стерется. А это вызовет проблему.

**Comment by Drkoles** [comment]
Ну теперь понял зачем это)
в общем чтобы скрипт работал только на постах добавлю проверку !is_archive()

**Comment by Drkoles** [comment]
Ну вот пока так. Пока не сделал чтобы отображались только заголовки первого уровня(не меняя при этом код скрипта)
https://github.com/Drkoles/Repos_orig/blob/master/eskju.jquery.fancyindex.zip

**Comment by aiiddqd** [comment]
залей сюда https://github.com/systemo-biz/jquery-fancyindex-wp-cp

**Comment by Drkoles** [comment]
Не могу залить. Нет доступа

**Comment by aiiddqd** [comment]
сделай пул реквест

**Comment by Drkoles** [comment]
сделал. Проверь)

**Comment by Drkoles** [comment]
Долго разбирался )

**Comment by aiiddqd** [comment]
zip не пойдет
без архива
птм что когда скачиваешь он и так в архиве. получается архив в архиве. сложно.

**Comment by Drkoles** [comment]
хорошо) сейчас перезалью

**Comment by Drkoles** [comment]
Ну вроде всё

**Comment by aiiddqd** [comment]
корень не тот.
надо чтобы папки тоже не было.
чтобы ключевой файл плагина был в корне.
иначе при закачке fh[bdf не будет работать.

**Comment by Drkoles** [comment]
понял

**Comment by Drkoles** [comment]
а readme нужен?

**Comment by Drkoles** [comment]
тот, в котором TODO

**Comment by aiiddqd** [comment]
да

**Comment by Drkoles** [comment]
ok

**Comment by Drkoles** [comment]
готово

**Comment by aiiddqd** [comment]
отлично )

**Comment by Drkoles** [comment]
Спасибо за подсказки)
Что дальше?)

**Comment by aiiddqd** [comment]
щас добавим тебя в систему и дам новое задание уже там
